"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import FloatField from "../FloatField";
import { apiBaseUrl, PORTAL_AUTH_COOKIE, PORTAL_AUTH_STORAGE_KEY } from "@/lib/api-client";

/**
 * Landing page for the invitation email. The link looks like
 *   /admin/accept-invite?token=<random>&email=<email>
 * The token was generated by POST /admin/portal-users and stored on the
 * portal_users row; the user sets a password here, which finalises the
 * account, clears the token, and signs them in.
 */
function AcceptInviteInner() {
  const params = useSearchParams();
  const token = params.get("token") || "";
  const email = params.get("email") || "";

  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [stage, setStage] = useState<"idle" | "submit" | "redirect">("idle");
  const [error, setError] = useState("");

  const busy = stage !== "idle";

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    if (!token) { setError("Missing invite token. Ask your admin to resend the invite."); return; }
    if (password.length < 8) { setError("Password must be at least 8 characters."); return; }
    if (password !== confirm) { setError("Passwords don't match."); return; }
    setStage("submit");
    try {
      const res = await fetch(`${apiBaseUrl()}/portal/accept-invite`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password, name: name.trim() || undefined }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(body?.message || body?.error || "Could not accept invite.");
        setStage("idle");
        return;
      }
      // Same shape as /portal/login — token + user + permissions. Persist
      // exactly like the login page does, then hard-redirect into /admin.
      const stored = {
        token: body.token,
        expires_at: body.expires_at ?? null,
        user: body.user,
        permissions: Array.isArray(body.permissions) ? body.permissions : [],
      };
      window.localStorage.setItem(PORTAL_AUTH_STORAGE_KEY, JSON.stringify(stored));
      const secure = window.location.protocol === "https:" ? "; Secure" : "";
      const expires = stored.expires_at ? `; Expires=${new Date(stored.expires_at).toUTCString()}` : "";
      document.cookie = `${PORTAL_AUTH_COOKIE}=${encodeURIComponent(body.token)}; Path=/; SameSite=Lax${expires}${secure}`;
      setStage("redirect");
      window.location.assign("/admin");
    } catch (err: any) {
      setError(err?.message || "Something went wrong.");
      setStage("idle");
    }
  }

  const label =
    stage === "submit" ? "Setting up your account…" :
    stage === "redirect" ? "Redirecting…" :
    "Accept invite & sign in";

  return (
    <div className="admin-login-wrap">
      <form className="admin-login-card" onSubmit={onSubmit}>
        <div className="admin-brand" style={{ marginBottom: 4, justifyContent: "center" }}>
          <Image
            src="/assets/subscribai-logo.png"
            alt="SubscribAI"
            width={160}
            height={40}
            priority
            style={{ height: "auto", width: "auto", maxHeight: 40 }}
          />
        </div>
        <h1 className="admin-login-title">You're invited</h1>
        <p className="admin-login-subtitle">
          {email ? <>Set a password for <strong>{email}</strong> to finish setting up your account.</> : "Set a password to finish setting up your account."}
        </p>

        {error && (
          <div className="admin-login-error">
            <i className="fa-solid fa-circle-exclamation" aria-hidden="true"></i>
            <span>{error}</span>
          </div>
        )}

        <FloatField
          id="name"
          label="Your name (optional)"
          type="text"
          icon="fa-user"
          autoComplete="name"
          disabled={busy}
          value={name}
          onChange={(e) => setName(e.target.value)}
        />

        <FloatField
          id="password"
          label="Password (min 8 characters)"
          type="password"
          icon="fa-key"
          autoComplete="new-password"
          required
          disabled={busy}
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />

        <FloatField
          id="confirm"
          label="Confirm password"
          type="password"
          icon="fa-key"
          autoComplete="new-password"
          required
          disabled={busy}
          value={confirm}
          onChange={(e) => setConfirm(e.target.value)}
        />

        <button
          type="submit"
          className="admin-btn admin-btn-primary"
          style={{ width: "100%", justifyContent: "center", gap: 10 }}
          disabled={busy || !token}
          aria-busy={busy}
        >
          {busy && <span className="admin-spinner" />}
          {label}
        </button>

        <p style={{ fontSize: "0.82rem", color: "var(--text-muted)", marginTop: 16, textAlign: "center" }}>
          <Link href="/admin/login" style={{ color: "var(--text-soft)" }}>Already have an account? Sign in →</Link>
        </p>
      </form>
    </div>
  );
}

export default function AcceptInvitePage() {
  return (
    <Suspense fallback={
      <div className="admin-login-wrap">
        <div className="admin-login-card" style={{ display: "grid", placeItems: "center", padding: 36 }}>
          <span className="admin-spinner lg" style={{ color: "var(--brand-300)" }} />
        </div>
      </div>
    }>
      <AcceptInviteInner />
    </Suspense>
  );
}
